"""Textual conditions t_c for every class (Section 1.2 / Eq. 2).

The paper conditions the diffusion model on p_c = E_CLIP^text(t_c) where t_c is
"either a simple prompt or a detailed sentence generated by an LLM".  We support
three modes so the contribution of the language prior is measurable:

    "classname"  : t_c = "a photo of a {name}."                (1 prompt)
    "template"   : the 80-prompt OpenAI CLIP ImageNet ensemble  (80 prompts)
    "llm"        : LLM-written visual descriptions              (K prompts)

The LLM descriptions are generated once and committed under
`cdfscil/assets/descriptions/<dataset>.json` so that a reproduction run needs no
API key and is byte-for-byte repeatable.  `generate_descriptions.py` regenerates
them from scratch against the Anthropic or OpenAI API; the exact instruction we
used lives in GENERATION_PROMPT below and in the `_meta` block of each asset.
"""
from __future__ import annotations

import json
from pathlib import Path

ASSET_DIR = Path(__file__).parent / "assets" / "descriptions"

# Prompt handed to the LLM when (re)generating the description asset.
GENERATION_PROMPT = """\
You are helping build text conditions for a class-conditional image diffusion
model and for CLIP text embeddings.

For the visual object category "{classname}", write exactly {k} short English
descriptions. Requirements:
  * Each description must start with "a photo of a {classname}" or
    "a photo of the {classname}" and then add concrete VISUAL attributes.
  * Mention colour, shape, texture, material, typical parts and typical
    surroundings - the things that make the category visually recognisable.
  * Vary the descriptions: different viewpoints, contexts, colours, instances.
  * One line each, no numbering, no extra commentary, max 25 words per line.
Return only the {k} lines."""

# The 80-prompt OpenAI ImageNet ensemble, as published with CLIP.
OPENAI_IMAGENET_TEMPLATES = [
    'a bad photo of a {}.', 'a photo of many {}.', 'a sculpture of a {}.',
    'a photo of the hard to see {}.', 'a low resolution photo of the {}.',
    'a rendering of a {}.', 'graffiti of a {}.', 'a bad photo of the {}.',
    'a cropped photo of the {}.', 'a tattoo of a {}.', 'the embroidered {}.',
    'a photo of a hard to see {}.', 'a bright photo of a {}.',
    'a photo of a clean {}.', 'a photo of a dirty {}.',
    'a dark photo of the {}.', 'a drawing of a {}.', 'a photo of my {}.',
    'the plastic {}.', 'a photo of the cool {}.', 'a close-up photo of a {}.',
    'a black and white photo of the {}.', 'a painting of the {}.',
    'a painting of a {}.', 'a pixelated photo of the {}.',
    'a sculpture of the {}.', 'a bright photo of the {}.',
    'a cropped photo of a {}.', 'a plastic {}.', 'a photo of the dirty {}.',
    'a jpeg corrupted photo of a {}.', 'a blurry photo of the {}.',
    'a photo of the {}.', 'a good photo of the {}.', 'a rendering of the {}.',
    'a {} in a video game.', 'a photo of one {}.', 'a doodle of a {}.',
    'a close-up photo of the {}.', 'a photo of a {}.', 'the origami {}.',
    'the {} in a video game.', 'a sketch of a {}.', 'a doodle of the {}.',
    'a origami {}.', 'a low resolution photo of a {}.', 'the toy {}.',
    'a rendition of the {}.', 'a photo of the clean {}.',
    'a photo of a large {}.', 'a rendition of a {}.',
    'a photo of a nice {}.', 'a photo of a weird {}.', 'a blurry photo of a {}.',
    'a cartoon {}.', 'art of a {}.', 'a sketch of the {}.', 'a embroidered {}.',
    'a pixelated photo of a {}.', 'itap of the {}.',
    'a jpeg corrupted photo of the {}.', 'a good photo of a {}.',
    'a plushie {}.', 'a photo of the nice {}.', 'a photo of the small {}.',
    'a photo of the weird {}.', 'the cartoon {}.', 'art of the {}.',
    'a drawing of the {}.', 'a photo of the large {}.',
    'a black and white photo of a {}.', 'the plushie {}.',
    'a dark photo of a {}.', 'itap of a {}.', 'graffiti of the {}.',
    'a toy {}.', 'itap of my {}.', 'a photo of a cool {}.',
    'a photo of a small {}.', 'a tattoo of the {}.',
]


def asset_path(dataset: str) -> Path:
    return ASSET_DIR / f"{dataset}.json"


def load_llm_descriptions(dataset: str, class_names: list[str],
                          keys: list[str] | None = None) -> list[list[str]]:
    """Return descriptions[c] for every class.

    `keys` lets miniImageNet look descriptions up by wnid (stable) instead of by
    the human-readable name.  Falls back to the class name if a key is missing,
    and says so loudly rather than silently degrading.
    """
    path = asset_path(dataset)
    if not path.exists():
        raise FileNotFoundError(
            f"{path} not found. Run:  python -m cdfscil.generate_descriptions "
            f"--dataset {dataset}")
    blob = json.load(open(path))
    data = blob["descriptions"]
    lookup = keys if keys is not None else class_names
    out, missing = [], []
    for k, name in zip(lookup, class_names):
        if k in data:
            out.append(list(data[k]))
        else:
            missing.append(k)
            out.append([f"a photo of a {name}."])
    if missing:
        raise KeyError(f"{len(missing)} classes missing from {path}: {missing[:8]}")
    return out


def build_prompts(mode: str, class_names: list[str], dataset: str,
                  keys: list[str] | None = None) -> list[list[str]]:
    if mode == "classname":
        return [[f"a photo of a {n}."] for n in class_names]
    if mode == "template":
        return [[t.format(n) for t in OPENAI_IMAGENET_TEMPLATES] for n in class_names]
    if mode == "llm":
        return load_llm_descriptions(dataset, class_names, keys)
    if mode == "llm+template":
        llm = load_llm_descriptions(dataset, class_names, keys)
        tpl = [[t.format(n) for t in OPENAI_IMAGENET_TEMPLATES] for n in class_names]
        return [a + b for a, b in zip(llm, tpl)]
    raise ValueError(f"unknown prompt mode {mode}")
