"""(Re)generate the LLM class-description asset.

The committed assets under `cdfscil/assets/descriptions/` were produced with
this exact prompt (`descriptions.GENERATION_PROMPT`); they are checked in so a
reproduction run needs no API key and is byte-for-byte repeatable.  Use this
script only if you want to regenerate them with a different LLM.

    export ANTHROPIC_API_KEY=...        # or OPENAI_API_KEY
    python -m cdfscil.generate_descriptions --dataset mini_imagenet --k 6

With `--provider template` it writes a deterministic attribute-free fallback
(the class name in a handful of photo templates) so the pipeline still runs
without any API access -- clearly marked as such in the asset's `_meta`.
"""
from __future__ import annotations

import argparse
import json
import os
import time
from pathlib import Path

from .data import build_benchmark
from .descriptions import ASSET_DIR, GENERATION_PROMPT
from .extract_features import load_classname_map

FALLBACK = [
    "a photo of a {}.",
    "a close-up photo of a {}.",
    "a photo of a {} in its typical setting.",
    "a bright, clear photo of a {}.",
    "a photo of one {}, showing its characteristic shape and colour.",
    "a detailed photograph of a {}.",
]


def call_anthropic(prompt: str, model: str) -> str:
    import anthropic
    client = anthropic.Anthropic()
    r = client.messages.create(model=model, max_tokens=1024,
                               messages=[{"role": "user", "content": prompt}])
    return "".join(b.text for b in r.content if b.type == "text")


def call_openai(prompt: str, model: str) -> str:
    from openai import OpenAI
    client = OpenAI()
    r = client.chat.completions.create(
        model=model, messages=[{"role": "user", "content": prompt}])
    return r.choices[0].message.content


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dataset", default="mini_imagenet")
    ap.add_argument("--data-root", default="data")
    ap.add_argument("--k", type=int, default=6)
    ap.add_argument("--provider", default="anthropic",
                    choices=["anthropic", "openai", "template"])
    ap.add_argument("--model", default=None)
    ap.add_argument("--out", default=None)
    args = ap.parse_args()

    model = args.model or {"anthropic": "claude-opus-5",
                           "openai": "gpt-4o"}.get(args.provider, "n/a")

    bench = build_benchmark(args.dataset, args.data_root,
                            load_classname_map(args.dataset))
    keys = bench.wnids if args.dataset == "mini_imagenet" else bench.class_names

    out = {}
    for key, name in zip(keys, bench.class_names):
        if args.provider == "template":
            out[key] = [t.format(name) for t in FALLBACK[:args.k]]
            continue
        prompt = GENERATION_PROMPT.format(classname=name, k=args.k)
        fn = call_anthropic if args.provider == "anthropic" else call_openai
        for attempt in range(4):
            try:
                txt = fn(prompt, model)
                break
            except Exception as e:                       # noqa: BLE001
                if attempt == 3:
                    raise
                print(f"  retry {attempt+1} for {name}: {e}")
                time.sleep(2 ** attempt)
        lines = [l.strip(" -*\t") for l in txt.splitlines() if l.strip()]
        lines = [l for l in lines if len(l.split()) >= 4][:args.k]
        if len(lines) < args.k:
            lines += [t.format(name) for t in FALLBACK[:args.k - len(lines)]]
        out[key] = lines
        print(f"  {key} ({name}): {len(lines)} descriptions")

    blob = {
        "_meta": {
            "dataset": args.dataset, "n_classes": len(out),
            "descriptions_per_class": args.k,
            "keyed_by": "wnid" if args.dataset == "mini_imagenet" else "classname",
            "generator": f"{args.provider}:{model}",
            "generation_prompt": GENERATION_PROMPT,
            "note": ("Regenerated by cdfscil.generate_descriptions. "
                     "Template provider = no LLM was used."),
        },
        "descriptions": out,
    }
    path = Path(args.out) if args.out else ASSET_DIR / f"{args.dataset}.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    json.dump(blob, open(path, "w"), indent=1)
    print(f"wrote {path} ({len(out)} classes)")


if __name__ == "__main__":
    main()
